In [1]:
import pandas as pd
path = '/home/daniel.lien/dev/homework/data/U.S._Chronic_Disease_Indicators__CDI___2023_Release copy.csv'
def read_data(file_path):
    return pd.read_csv(file_path)
df_all = read_data(path)
df_all.head()

/tmp/ipykernel_86383/1925007356.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(file_path)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2010,2010,OR,Oregon,NVSS,Cardiovascular Disease,Mortality from heart failure,NaN,NaN,Number,...,41,CVD,CVD1_4,NMBR,RACE,AIAN,NaN,NaN,NaN,NaN
1,2019,2019,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,4,ALC,ALC1_1,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
2,2019,2019,OH,Ohio,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,39,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
3,2019,2019,US,United States,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,59,ALC,ALC1_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
4,2015,2015,VI,Virgin Islands,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,78,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN

In [2]:
df = df_all[df_all['Topic'] == 'Chronic Kidney Disease']

In [4]:
columns_to_drop = ['Response', 
            'StratificationCategory2',
            'Stratification2',
            'StratificationCategory3',
            'Stratification3',
            'ResponseID',
            'StratificationCategoryID2', 
            'StratificationID2',         
            'StratificationCategoryID3',
            'StratificationID3',
            'YearEnd',
            'LocationAbbr',
            'DataSource',
            'DataValueAlt',
            'DataValueFootnoteSymbol',
            'HighConfidenceLimit',
            'LowConfidenceLimit',
            'LocationID',
            'TopicID',
            'DataValueTypeID'
    ]
df = df.drop(columns=columns_to_drop)

In [5]:
df.head()

,YearStart,LocationDesc,Topic,Question,DataValueUnit,DataValueType,DataValue,DatavalueFootnote,StratificationCategory1,Stratification1,GeoLocation,QuestionID,StratificationCategoryID1,StratificationID1
1109,2012,Alaska,Chronic Kidney Disease,Mortality with end-stage renal disease,NaN,Number,194,NaN,Gender,Male,POINT (-147.72205903599973 64.84507995700051),CKD1_0,GENDER,GENM
1110,2016,Alaska,Chronic Kidney Disease,Mortality with end-stage renal disease,NaN,Number,142,NaN,Gender,Male,POINT (-147.72205903599973 64.84507995700051),CKD1_0,GENDER,GENM
1111,2018,Alaska,Chronic Kidney Disease,Mortality with end-stage renal disease,NaN,Number,20,NaN,Race/Ethnicity,Asian or Pacific Islander,POINT (-147.72205903599973 64.84507995700051),CKD1_0,RACE,API
1112,2010,Alabama,Chronic Kidney Disease,Mortality with end-stage renal disease,NaN,Number,2138,NaN,Gender,Female,POINT (-86.63186076199969 32.84057112200048),CKD1_0,GENDER,GENF
1113,2017,Alabama,Chronic Kidney Disease,Mortality with end-stage renal disease,NaN,Number,1801,NaN,Gender,Male,POINT (-86.63186076199969 32.84057112200048),CKD1_0,GENDER,GENM

In [6]:
# Group by Question and Question ID to Create Question Map
question_ID_map = df.groupby("Question")['QuestionID'].unique().apply(sorted).to_dict()
# pd.DataFrame([(k,v) for k, v in question_ID_map.items()], columns=['Question', 'QuestionID'])
question_df = (pd.DataFrame([(k, v) for k, ids in question_ID_map.items() for v in ids], 
                             columns=['Question', 'QuestionID'])
               .sort_values(by='QuestionID')
               .reset_index(drop=True))

# Print the DataFrame nicely
print(question_df)

                                            Question QuestionID
0             Mortality with end-stage renal disease     CKD1_0
1       Incidence of treated end-stage renal disease     CKD2_1
2  Incidence of treated end-stage renal disease a...     CKD2_2
3  Prevalence of chronic kidney disease among adu...     CKD3_0

In [7]:
output_dir = '/home/daniel.lien/dev/homework/data/CKD.csv'
df.to_csv(output_dir, index=False)