# Exploratory Data Analysis for Chronic Disease Indicator - COPD

In [5]:
# Imports
import pandas as pd

In [59]:
# Read in the Data
path = '/home/daniel.lien/dev/homework/data/U.S._Chronic_Disease_Indicators__CDI___2023_Release copy.csv'
def read_data(file_path):
    return pd.read_csv(file_path)
df = read_data(path)
df_copy = df.copy()

/tmp/ipykernel_1197714/1714170376.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(file_path)

In [60]:
# Ensure csv is loaded by checking the shape of the Dataset
print(f"There are {df.shape[0]} rows and {df.shape[1]} cols")

There are 1185676 rows and 34 cols

In [61]:
# Check the Columns
df.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'Response', 'DataValueUnit', 'DataValueType',
       'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DatavalueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'StratificationCategory2',
       'Stratification2', 'StratificationCategory3', 'Stratification3',
       'GeoLocation', 'ResponseID', 'LocationID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'StratificationCategoryID1', 'StratificationID1',
       'StratificationCategoryID2', 'StratificationID2',
       'StratificationCategoryID3', 'StratificationID3'],
      dtype='object')

In [63]:
# Check Unique Values for each column
def check_unique_values(df):
    for col in df.columns:
        print(f'{col}: {df[col].unique()}')
        
check_unique_values(df) #Save the output to a file for review

YearStart: [2010 2019 2015 2020 2018 2013 2011 2012 2016 2014 2017 2021 2009 2008
 2001 2007]
YearEnd: [2010 2019 2015 2020 2018 2013 2011 2012 2016 2014 2017 2021 2001 2008
 2009 2007]
LocationAbbr: ['OR' 'AZ' 'OH' 'US' 'VI' 'AL' 'DE' 'FL' 'KS' 'MS' 'NJ' 'PA' 'SD' 'VT'
 'AK' 'AR' 'CO' 'CT' 'DC' 'GA' 'HI' 'IA' 'ID' 'IN' 'KY' 'LA' 'MA' 'ME'
 'MI' 'MN' 'MO' 'MT' 'ND' 'NE' 'NH' 'NM' 'NV' 'NY' 'OK' 'RI' 'SC' 'TN'
 'TX' 'UT' 'VA' 'WA' 'WI' 'WV' 'WY' 'CA' 'NC' 'GU' 'IL' 'PR' 'MD']
LocationDesc: ['Oregon' 'Arizona' 'Ohio' 'United States' 'Virgin Islands' 'Alabama'
 'Delaware' 'Florida' 'Kansas' 'Mississippi' 'New Jersey' 'Pennsylvania'
 'South Dakota' 'Vermont' 'Alaska' 'Arkansas' 'Colorado' 'Connecticut'
 'District of Columbia' 'Georgia' 'Hawaii' 'Iowa' 'Idaho' 'Indiana'
 'Kentucky' 'Louisiana' 'Massachusetts' 'Maine' 'Michigan' 'Minnesota'
 'Missouri' 'Montana' 'North Dakota' 'Nebraska' 'New Hampshire'
 'New Mexico' 'Nevada' 'New York' 'Oklahoma' 'Rhode Island'
 'South Carolina' 'Tennessee' 'Texas' 'Utah' 'Virginia' 'Washington'
 'Wisconsin' 'West Virginia' 'Wyoming' 'California' 'North Carolina'
 'Guam' 'Illinois' 'Puerto Rico' 'Maryland']
DataSource: ['NVSS' 'YRBSS' 'PRAMS' 'BRFSS' 'SEDD; SID'
 'Statewide central cancer registries' 'Death Certificate' 'USRDS'
 'CMS Part A Claims Data' 'ACS 1-Year Estimates' 'CMS CCW' 'HRSA, UDS'
 'WFRS' 'NVSS, Mortality' 'Legal Research' 'APIS' 'AEDS'
 'Birth Certificate, NVSS' 'NSCH' 'Current Population Survey'
 'CDC Breastfeeding Report Card' 'CDC School Health Profiles'
 'National Immunization Survey' 'mPINC'
 "CDC Children's Food Environment State Indicator Report"
 "USDA National Farmers' Market Directory" 'InfoUSA; USDA' 'ASHW' 'STATE'
 'ACS 5-Year Estimates' 'ANRF']
Topic: ['Cardiovascular Disease' 'Alcohol' 'Arthritis' 'Asthma' 'Cancer'
 'Chronic Kidney Disease' 'Chronic Obstructive Pulmonary Disease'
 'Mental Health' 'Tobacco' 'Overarching Conditions' 'Oral Health'
 'Reproductive Health' 'Diabetes' 'Immunization'
 'Nutrition, Physical Activity, and Weight Status' 'Disability'
 'Older Adults']
Question: ['Mortality from heart failure' 'Alcohol use among youth'
 'Alcohol use before pregnancy' 'Binge drinking prevalence among youth'
 'Chronic liver disease mortality'
 'Adults aged >= 18 years with arthritis who have taken a class to learn how to manage arthritis symptoms'
 'Arthritis among adults aged >= 18 years who are obese'
 'Emergency department visit rate for asthma'
 'Hospitalizations for asthma' 'Asthma mortality rate'
 'Invasive cancer of the oral cavity or pharynx, incidence'
 'Cancer of the oral cavity and pharynx, mortality'
 'Invasive cancer of the prostate, incidence'
 'Cancer of the prostate, mortality'
 'Invasive cancer (all sites combined), incidence'
 'Invasive cancer (all sites combined), mortality'
 'Invasive cancer of the female breast, incidence' 'Melanoma, mortality'
 'Cancer of the female breast, mortality'
 'Invasive cancer of the cervix, incidence'
 'Cancer of the female cervix, mortality'
 'Cancer of the colon and rectum (colorectal), incidence'
 'Cancer of the colon and rectum (colorectal), mortality'
 'Cancer of the lung and bronchus, incidence'
 'Cancer of the lung and bronchus, mortality'
 'Invasive melanoma, incidence' 'Mortality with end-stage renal disease'
 'Incidence of treated end-stage renal disease'
 'Incidence of treated end-stage renal disease attributed to diabetes'
 'Mortality with chronic obstructive pulmonary disease as underlying cause among adults aged >= 45 years'
 'Mortality from coronary heart disease'
 'At least 14 recent mentally unhealthy days among women aged 18-44 years'
 'Arthritis among adults aged >= 18 years who have diabetes'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years who smoke'
 'Arthritis among adults aged >= 18 years'
 'Quit attempts in the past year among current smokers'
 'Binge drinking frequency among adults aged >= 18 years who binge drink'
 'Recent activity limitation among adults aged >= 18 years'
 'High cholesterol prevalence among adults aged >= 18 years'
 'Current cigarette smoking among women aged 18-44 years'
 'Physical inactivity among adults aged >= 18 years with arthritis'
 'Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >= 45 years'
 'Prevalence of sufficient sleep among adults aged >= 18 years'
 'Binge drinking prevalence among women aged 18-44 years'
 'Binge drinking intensity among adults aged >= 18 years who binge drink'
 'Fair or poor health among adults aged >= 18 years with arthritis'
 'Binge drinking prevalence among adults aged >= 18 years'
 'Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50-75 years'
 'Current health care coverage among women aged 18-44 years'
 'Recent physically unhealthy days among adults aged >= 18 years'
 'Six or more teeth lost among adults aged >= 65 years'
 'Current smoking among adults aged >= 18 years'
 'Heavy drinking among adults aged >= 18 years'
 'Timeliness of routine health care checkup among women aged 18-44 years'
 'Prevalence of diagnosed diabetes among adults aged >= 18 years'
 'Recent mentally unhealthy days among adults aged >= 18 years'
 'Cholesterol screening among adults aged >= 18 years'
 'Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes'
 'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis'
 'Arthritis among adults aged >= 18 years who have heart disease'
 'Hospitalization for chronic obstructive pulmonary disease as any diagnosis'
 'Heavy drinking among women aged 18-44 years'
 'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis among Medicare-eligible persons aged >= 65 years'
 'Visits to dentist or dental clinic among adults aged >= 18 years'
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with asthma'
 'All teeth lost among adults aged >= 65 years'
 'Influenza vaccination among noninstitutionalized adults aged >= 18 years'
 'Foot examination among adults aged >= 18 years with diagnosed diabetes'
 'Fair or poor self-rated health status among adults aged >= 18 years'
 'Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes'
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes'
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with asthma'
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes'
 'Awareness of high blood pressure among women aged 18-44 years'
 'Healthy weight among adults aged >= 18 years'
 'Awareness of high blood pressure among adults aged >= 18 years'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes'
 'Prevalence of chronic kidney disease among adults aged >= 18 years'
 'Current lack of health insurance among adults aged 18-64 years'
 'Hospitalization for chronic obstructive pulmonary disease as any diagnosis among Medicare-eligible persons aged >= 65 years'
 'Dilated eye examination among adults aged >= 18 years with diagnosed diabetes'
 'Mortality from total cardiovascular diseases'
 'Mammography use among women aged 50-74 years'
 'Overweight or obesity among women aged 18-44 years'
 'Papanicolaou smear use among adult women aged 21-65 years'
 'Work limitation due to arthritis among adults aged 18-64 years who have doctor-diagnosed arthritis'
 'Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes'
 'Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes'
 'Overweight or obesity among adults aged >= 18 years'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with asthma'
 'Emergency department visit rate for chronic obstructive pulmonary disease as first-listed diagnosis'
 'Self-rated health status among women aged 18-44 years'
 'Emergency department visit rate for chronic obstructive pulmonary disease as any diagnosis'
 'No tooth loss among adults aged 18-64 years'
 'No leisure-time physical activity among adults aged >= 18 years'
 'Obesity among adults aged >= 18 years'
 'Recent Papanicolaou smear use among women aged 21-44 years'
 'Current asthma prevalence among adults aged >= 18 years'
 'Diabetes prevalence among women aged 18-44 years'
 'Current smokeless tobacco use among adults aged >= 18 years'
 'Mortality from diseases of the heart'
 'Mortality from cerebrovascular disease (stroke)'
 'Hospitalization for stroke'
 'Hospitalization for heart failure among Medicare-eligible persons aged >= 65 years'
 'Hospitalization for acute myocardial infarction'
 'Mortality due to diabetes reported as any listed cause of death'
 'Mortality with diabetic ketoacidosis reported as any listed cause of death'
 'Prevalence of pre-pregnancy diabetes'
 'Amputation of a lower extremity attributable to diabetes'
 'Hospitalization with diabetes as a listed diagnosis'
 'Disability among adults aged >= 65 years'
 'Meeting aerobic physical activity guidelines among high school students'
 'Soda consumption among high school students'
 'Obesity among high school students'
 'Television viewing among high school students'
 'Computer use among high school students'
 'Overweight or obesity among high school students'
 'Healthy weight among high school students'
 'Median daily frequency of fruit consumption among high school students'
 'Median daily frequency of vegetable consumption among high school students'
 'Hospitalization for hip fracture among Medicare-eligible persons aged >= 65 years'
 'Premature mortality among adults aged 45-64 years'
 'Prevalence of 2 or more chronic conditions among Medicare-enrolled persons aged >= 65 years'
 'Preventive dental care before pregnancy'
 'Oral health services at Federally Qualified Health Centers'
 'Population served by community water systems that receive fluoridated drinking water'
 'Poverty' 'Life expectancy at age 65 years' 'Postpartum checkup'
 'Folic acid supplementation' 'Current cigarette smoking among youth'
 'Cigarette smoking before pregnancy'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with asthma'
 'Activity limitation due to arthritis among adults aged >= 18 years who have doctor-diagnosed arthritis'
 'Local authority to regulate alcohol outlet density'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years who smoke'
 'Amount of alcohol excise tax by beverage type (beer)'
 'Amount of alcohol excise tax by beverage type (wine)'
 'Amount of alcohol excise tax by beverage type (distilled spirits)'
 'Commercial host (dram shop) liability laws'
 'Per capita alcohol consumption among persons aged >= 14 years'
 'Proportion of older adults aged >= 65 years who are up to date on a core set of clinical preventive services'
 'Asthma prevalence among women aged 18-44 years'
 'Severe joint pain due to arthritis among adults aged >= 18 years who have doctor-diagnosed arthritis'
 'Prevalence of chronic obstructive pulmonary disease among adults >= 18'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes'
 'Prevalence of chronic obstructive pulmonary disease among adults >= 45 years'
 'Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes'
 'Taking medicine for high blood pressure control among adults aged >= 18 years with high blood pressure'
 'Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course'
 'Postpartum depressive symptoms' 'Pre-pregnancy hypertension'
 'Proportion of older adults aged 50-64 years who are up to date on a core set of clinical preventive services'
 'Prevalence of gestational diabetes'
 'Dental visits among children and adolescents aged 1-17 years'
 'High school completion among adults aged 18-24 years'
 'High school completion among women aged 18-44 years'
 'Health insurance coverage before pregnancy'
 'Poverty among women aged 18-44 years'
 'Participation in daily school physical education classes among high school students'
 'Live births occurring at Baby Friendly Facilities'
 'Secondary schools that allow community-sponsored use of physical activity facilities by youth outside of normal school hours'
 'Infants breastfed at 6 months'
 'Receiving formula supplementation within the first 2 days of life among breastfed infants'
 'Mean maternity practices in infant nutrition care (mPINC) score'
 'Secondary schools that allow students to purchase soda or fruit drinks'
 'Secondary schools that offer less healthy foods as competitive foods'
 'Presence of regulations pertaining to screen time in early care and education settings'
 'Secondary schools that allow students to purchase sports drinks'
 'State child care regulation supports onsite breastfeeding'
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease or stroke'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease'
 'Prevalence of current smoking among adults >= 18 with diagnosed chronic obstructive pulmonary disease'
 'Presence of regulations pertaining to avoiding sugar in early care and education settings'
 'Number of farmers markets per 100,000 residents'
 'Census tracts with healthier food retailers within � mile of boundary'
 'Farmers markets that accept Women and Infant Children (WIC) farmers market nutrition program coupons'
 'Presence of regulations pertaining to serving fruit in early care and education settings'
 'Presence of regulations pertaining to serving vegetables in early care and education settings'
 'Farmers markets that accept Supplemental Nutrition Assistance Program (SNAP) benefits'
 'Life expectancy at birth' 'Sale of cigarette packs'
 'Amount of tobacco product excise tax'
 'Current smokeless tobacco use among youth'
 'Preventive dental visits among children and adolescents aged 1-17 years'
 'Gini Index of income inequality'
 'States that allow stronger local tobacco control and prevention laws'
 'States with strong polices that require retail licenses to sell tobacco products'
 'Proportion of the population protected by a comprehensive smoke-free policy prohibiting smoking in all indoor areas of workplaces and public places, including restaurants and bars'
 'Secondary schools that have a comprehensive tobacco-free school policy in place'
 'Percent tobacco revenue to fund at CDC recommended level'
 'Prevalence of current smoking among adults >= 45 years with diagnosed chronic obstructive pulmonary disease'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease'
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease or stroke'
 'Meeting aerobic physical activity guidelines for additional and more extensive health benefits among adults aged >= 18 years'
 'Prevalence of activity limitation among adults >= 45 years with diagnosed chronic obstructive pulmonary disease'
 'Influenza vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease'
 'Prevalence of activity limitation among adults >= 18 with diagnosed chronic obstructive pulmonary disease'
 'Meeting aerobic physical activity guidelines for substantial health benefits and for muscle-strengthening activity among adults aged >= 18 years'
 'Meeting aerobic physical activity guidelines for substantial health benefits among adults aged >= 18 years'
 'Median daily frequency of vegetable consumption among adults aged >= 18 years'
 'Median daily frequency of fruit consumption among adults aged >= 18 years']
Response: [nan]
DataValueUnit: [nan '%' 'cases per 100,000' 'cases per 10,000' 'Number'
 'cases per 1,000,000' 'per 100,000' 'cases per 1,000' 'Years' '$'
 'gallons' 'per 100,000 residents' 'pack sales per capita']
DataValueType: ['Number' 'Crude Prevalence' 'Age-adjusted Rate' 'Crude Rate'
 'Average Annual Number' 'Average Annual Crude Rate'
 'Average Annual Age-adjusted Rate'
 'Adjusted by age, sex, race and ethnicity' 'Age-adjusted Prevalence'
 'Mean' 'Age-adjusted Mean' 'Median' 'Percent'
 'Local control of the regulation of alcohol outlet density' 'US Dollars'
 'Commercial host (dram shop) liability status for alcohol service'
 'Per capita alcohol consumption' 'Prevalence' 'Yes/No']
DataValue: ['30' '29.5' '22.5' ... '683.6' '103.1' '97.9']
DataValueAlt: [  30.    29.5   22.5 ... 1029.8  767.8  683.6]
DataValueFootnoteSymbol: [nan '-' '~' '&' '**' '^^^' '���' '^^' '****' '~~~~' '��' '*' '~~' '�,�'
 '�' '###' '##' '***']
DatavalueFootnote: [nan 'No data available'
 'Data not shown because of too few respondents or cases'
 'Less than 60 respondents, interpret with caution'
 'US estimate/number is based on fewer than 50 states and the District of Columbia'
 'DC was not rated for this measure because the measure addresses state versus local authority and does not apply to the District of Columbia'
 'Estimate is based on the first 3 quarters of 2015 and is not directly comparable to estimates in prior years due to changes in ICD codes'
 'State directly controlled the sale of (beer/wine/distilled spirits) at the retail and/or wholesale levels. State prices for (beer/wine/distilled spirits) combined both markups and taxes, so tax rates for this beverage type could not be determined.'
 'Sample size of denominator and/or age group for age-standardization is less than 50 or relative standard error is more than 30%'
 'The state registry opted not to present state-specific estimates for this race/ethnicity group'
 'Per capita alcohol consumption was calculated using (1) alcohol beverage sales data, either collected directly from states or provided by beverage industry sources (numerator); and (2) population data from the U.S. Census Bureau (denominator).'
 '50 States + DC: US Median'
 'A confidence interval for this location is not available because a census was used instead of a sample for their surveys'
 'Data cannot be calculated'
 'Population served by CWS exceeded the US Census state population estimate; number of persons was reduced by the ratio of the population estimate to the CWS population estimate. Complete data were not available from WFRS; state provided other information.'
 'Population served by CWS exceeded the US Census state population estimate; number of persons was reduced by the ratio of the population estimate to the CWS population estimate'
 'Median frequency (50th percentile) reported with quartiles (25th & 75th percentiles)'
 'Estimate is 0.0% because no cases were reported with this condition'
 'US Median is not available because the number of participating states is <30 (excludes states with sample size below 50 or relative standard error above 30%)']
LowConfidenceLimit: [  nan  24.9  17.  ... 382.  978.  897.2]
HighConfidenceLimit: [   nan   34.7   29.1 ...  782.5  600.4 1043.5]
StratificationCategory1: ['Race/Ethnicity' 'Gender' 'Overall']
Stratification1: ['American Indian or Alaska Native' 'Female' 'Male' 'Asian, non-Hispanic'
 'White, non-Hispanic' 'Overall' 'Hispanic' 'Black, non-Hispanic'
 'Asian or Pacific Islander' 'Multiracial, non-Hispanic'
 'Other, non-Hispanic']
StratificationCategory2: [nan]
Stratification2: [nan]
StratificationCategory3: [nan]
Stratification3: [nan]
GeoLocation: ['POINT (-120.15503132599969 44.56744942400047)'
 'POINT (-111.76381127699972 34.865970280000454)'
 'POINT (-82.40426005599966 40.06021014100048)' nan
 'POINT (-64.896335 18.335765)'
 'POINT (-86.63186076199969 32.84057112200048)'
 'POINT (-75.57774116799965 39.008830667000495)'

## Data Cleaning - Chronic Obstructive Pulmonary Disease (COPD)

In [64]:
# Begin Disease Specified Cleaning
df = df_copy.copy()
df.shape #should give (309215, 34)

(1185676, 34)

In [65]:
df.isnull().sum() #Check for missing values from entire dataset

YearStart                          0
YearEnd                            0
LocationAbbr                       0
LocationDesc                       0
DataSource                         0
Topic                              0
Question                           0
Response                     1185676
DataValueUnit                 152123
DataValueType                      0
DataValue                     378734
DataValueAlt                  381098
DataValueFootnoteSymbol       791966
DatavalueFootnote             791966
LowConfidenceLimit            503296
HighConfidenceLimit           503296
StratificationCategory1            0
Stratification1                    0
StratificationCategory2      1185676
Stratification2              1185676
StratificationCategory3      1185676
Stratification3              1185676
GeoLocation                    10166
ResponseID                   1185676
LocationID                         0
TopicID                            0
QuestionID                         0
DataValueTypeID                    0
StratificationCategoryID1          0
StratificationID1                  0
StratificationCategoryID2    1185676
StratificationID2            1185676
StratificationCategoryID3    1185676
StratificationID3            1185676
dtype: int64

In [ ]:
# Drop Columns from entire dataset that are missing = Num of missing values == num of rows --> Completely empty
df = df.drop(columns=[
            'Response', 
            'StratificationCategory2',
            'Stratification2',
            'StratificationCategory3',
            'Stratification3',
            'ResponseID',
            'StratificationCategoryID2', 
            'StratificationID2',         
            'StratificationCategoryID3',
            'StratificationID3'         
        ])
print(df.shape)
#should be (1185676, 24) - 10 cols were dropped

(1185676, 24)

In [67]:
# Now filter entier dataset for topic = 'Chronic Obstructive Pulmonary Disease'
topic = 'Chronic Obstructive Pulmonary Disease'
df_copd = df[df['Topic'] == topic]
print(df_copd.shape)
# df_copd.head()
# (1185676, 24) to (152874, 24) - about 12.9% of data is related to COPD

(152874, 24)

In [68]:
df_copd.isnull().sum()

YearStart                        0
YearEnd                          0
LocationAbbr                     0
LocationDesc                     0
DataSource                       0
Topic                            0
Question                         0
DataValueUnit                28338
DataValueType                    0
DataValue                    58290
DataValueAlt                 58290
DataValueFootnoteSymbol      92351
DatavalueFootnote            92351
LowConfidenceLimit           76665
HighConfidenceLimit          76665
StratificationCategory1          0
Stratification1                  0
GeoLocation                   1098
LocationID                       0
TopicID                          0
QuestionID                       0
DataValueTypeID                  0
StratificationCategoryID1        0
StratificationID1                0
dtype: int64

In [70]:
# Drop More columns that are not needed for COPD
columns_to_drop = [
    'YearEnd',
    'LocationAbbr',
    'DataSource',
    'DataValueAlt',
    'DataValueFootnoteSymbol',
    'DatavalueFootnote',
    'HighConfidenceLimit',
    'LowConfidenceLimit',
    'LocationID',
    'TopicID',
    'DataValueTypeID'
]

df_copd = df_copd.drop(columns=columns_to_drop)

# # From 34 columns to 13 columns - correct
df_copd.shape

(152874, 13)

In [71]:
df_copd.isnull().sum()

YearStart                        0
LocationDesc                     0
Topic                            0
Question                         0
DataValueUnit                28338
DataValueType                    0
DataValue                    58290
StratificationCategory1          0
Stratification1                  0
GeoLocation                   1098
QuestionID                       0
StratificationCategoryID1        0
StratificationID1                0
dtype: int64

In [46]:
# Last Check
df_copd.head()

,YearStart,LocationDesc,Topic,Question,DataValueUnit,DataValueType,DataValue,StratificationCategory1,Stratification1,Geolocation,QuestionID,StratificationCategoryID1,StratificationID1
14201,2019,Arizona,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,"cases per 1,000",Crude Rate,58.19,Race/Ethnicity,Hispanic,POINT (-111.76381127699972 34.865970280000454),COPD03,RACE,HIS
14214,2019,Arizona,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,"cases per 100,000",Age-adjusted Rate,NaN,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD05,RACE,HAPI
14217,2019,Arizona,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,66.00,Race/Ethnicity,"American Indian or Alaska Native, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD06,RACE,AIAN
14222,2019,California,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,58.00,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-120.99999953799971 37.63864012300047),COPD06,RACE,HAPI
14243,2019,Arkansas,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,4.50,Age,Age 18-44,POINT (-92.27449074299966 34.74865012400045),COPD01,AGE,AGE1844

In [72]:
# Reset Index
df_copd.reset_index(drop=True, inplace=True)

In [51]:
# save to csv
output_dir = '/home/daniel.lien/dev/homework/data/cleaned_copd_data_2.csv'
df_copd.to_csv(output_dir, index=False)

In [73]:
#create a working copy
df = df_copd.copy()
print(df.shape)
df.head()

(152874, 13)

,YearStart,LocationDesc,Topic,Question,DataValueUnit,DataValueType,DataValue,StratificationCategory1,Stratification1,GeoLocation,QuestionID,StratificationCategoryID1,StratificationID1
0,2014,Alaska,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,NaN,Number,89,Gender,Male,POINT (-147.72205903599973 64.84507995700051),COPD1_1,GENDER,GENM
1,2020,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,NaN,Number,3346,Overall,Overall,POINT (-86.63186076199969 32.84057112200048),COPD1_1,OVERALL,OVR
2,2012,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,NaN,Number,252,Race/Ethnicity,"Black, non-Hispanic",POINT (-86.63186076199969 32.84057112200048),COPD1_1,RACE,BLK
3,2015,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,NaN,Number,1617,Gender,Male,POINT (-86.63186076199969 32.84057112200048),COPD1_1,GENDER,GENM
4,2017,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,NaN,Number,348,Race/Ethnicity,"Black, non-Hispanic",POINT (-86.63186076199969 32.84057112200048),COPD1_1,RACE,BLK

In [74]:
df['DataValueType'].unique()

array(['Number', 'Age-adjusted Rate', 'Crude Rate', 'Crude Prevalence',
       'Age-adjusted Prevalence'], dtype=object)

In [75]:
df['Question'].unique()

array(['Mortality with chronic obstructive pulmonary disease as underlying cause among adults aged >= 45 years',
       'Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >= 45 years',
       'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis',
       'Hospitalization for chronic obstructive pulmonary disease as any diagnosis',
       'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis among Medicare-eligible persons aged >= 65 years',
       'Hospitalization for chronic obstructive pulmonary disease as any diagnosis among Medicare-eligible persons aged >= 65 years',
       'Emergency department visit rate for chronic obstructive pulmonary disease as first-listed diagnosis',
       'Emergency department visit rate for chronic obstructive pulmonary disease as any diagnosis',
       'Prevalence of chronic obstructive pulmonary disease among adults >= 18',
       'Prevalence of chronic obstructive pulmonary disease among adults >= 45 years',
       'Prevalence of current smoking among adults >= 18 with diagnosed chronic obstructive pulmonary disease',
       'Prevalence of current smoking among adults >= 45 years with diagnosed chronic obstructive pulmonary disease',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease',
       'Prevalence of activity limitation among adults >= 45 years with diagnosed chronic obstructive pulmonary disease',
       'Influenza vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease',
       'Prevalence of activity limitation among adults >= 18 with diagnosed chronic obstructive pulmonary disease'],
      dtype=object)

In [76]:
question_value_dict = df.groupby('Question')['DataValueType'].unique().apply(list).to_dict()

pd.DataFrame([(k, v) for k, v in question_value_dict.items()], columns=['Question', 'DataValueTypes'])

,Question,DataValueTypes
0,Emergency department visit rate for chronic ob...,"[Number, Crude Rate, Age-adjusted Rate]"
1,Emergency department visit rate for chronic ob...,"[Number, Age-adjusted Rate, Crude Rate]"
2,Hospitalization for chronic obstructive pulmon...,"[Number, Age-adjusted Rate, Crude Rate]"
3,Hospitalization for chronic obstructive pulmon...,"[Age-adjusted Rate, Crude Rate, Number]"
4,Hospitalization for chronic obstructive pulmon...,"[Number, Crude Rate, Age-adjusted Rate]"
5,Hospitalization for chronic obstructive pulmon...,"[Number, Age-adjusted Rate, Crude Rate]"
6,Influenza vaccination among noninstitutionaliz...,"[Age-adjusted Prevalence, Crude Prevalence]"
7,Mortality with chronic obstructive pulmonary d...,"[Number, Age-adjusted Rate, Crude Rate]"
8,Mortality with chronic obstructive pulmonary d...,"[Number, Age-adjusted Rate, Crude Rate]"
9,Pneumococcal vaccination among noninstitutiona...,"[Crude Prevalence, Age-adjusted Prevalence]"
10,Prevalence of activity limitation among adults...,"[Crude Prevalence, Age-adjusted Prevalence]"
11,Prevalence of activity limitation among adults...,"[Crude Prevalence, Age-adjusted Prevalence]"
12,Prevalence of chronic obstructive pulmonary di...,"[Crude Prevalence, Age-adjusted Prevalence]"
13,Prevalence of chronic obstructive pulmonary di...,"[Age-adjusted Prevalence, Crude Prevalence]"
14,Prevalence of current smoking among adults >= ...,"[Age-adjusted Prevalence, Crude Prevalence]"
15,Prevalence of current smoking among adults >= ...,"[Crude Prevalence, Age-adjusted Prevalence]"

In [ ]:
### Given this dataset, attempt to create a new df with more specific responses
"""
Year, Location, Topic, Question, 



Sex 
Grade - does not exist in COPD
Overall
Age
Race/Ethnicity
"""

Pivot Table here

In [53]:
df.head()

,YearStart,LocationDesc,Topic,Question,DataValueUnit,DataValueType,DataValue,StratificationCategory1,Stratification1,Geolocation,QuestionID,StratificationCategoryID1,StratificationID1
0,2019,Arizona,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,"cases per 1,000",Crude Rate,58.19,Race/Ethnicity,Hispanic,POINT (-111.76381127699972 34.865970280000454),COPD03,RACE,HIS
1,2019,Arizona,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,"cases per 100,000",Age-adjusted Rate,NaN,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD05,RACE,HAPI
2,2019,Arizona,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,66.00,Race/Ethnicity,"American Indian or Alaska Native, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD06,RACE,AIAN
3,2019,California,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,58.00,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-120.99999953799971 37.63864012300047),COPD06,RACE,HAPI
4,2019,Arkansas,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,4.50,Age,Age 18-44,POINT (-92.27449074299966 34.74865012400045),COPD01,AGE,AGE1844

In [56]:
pivot_df = df.pivot_table(
    index=["YearStart", "LocationDesc", "Topic", "Question", "DataValueType", "DataValueUnit"], 
    columns="Stratification1",
    values="DataValue",
    aggfunc="mean"  # Adjust as needed
).reset_index()

pivot_df.head()

Stratification1,YearStart,LocationDesc,Topic,Question,DataValueType,DataValueUnit,Age 18-44,Age 45-64,Age >=65,"American Indian or Alaska Native, non-Hispanic","Asian or Pacific Islander, non-Hispanic","Asian, non-Hispanic","Black, non-Hispanic",Female,"Hawaiian or Pacific Islander, non-Hispanic",Hispanic,Male,"Multiracial, non-Hispanic",Overall,"White, non-Hispanic"
0,2019,Alabama,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,Age-adjusted Prevalence,%,NaN,NaN,NaN,15.9,NaN,NaN,7.0,10.3,NaN,NaN,8.2,NaN,9.3,9.9
1,2019,Alabama,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,Crude Prevalence,%,5.8,11.4,15.9,17.1,NaN,NaN,7.0,11.0,NaN,NaN,8.7,NaN,9.9,11.0
2,2019,Alabama,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Age-adjusted Rate,"cases per 100,000",NaN,NaN,NaN,NaN,NaN,NaN,84.8,138.6,NaN,NaN,178.3,NaN,154.5,178.5
3,2019,Alabama,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Crude Rate,"cases per 100,000",NaN,46.5,335.6,NaN,NaN,NaN,77.1,154.1,NaN,NaN,171.6,NaN,162.2,198.3
4,2019,Alabama,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,NaN,593.0,2852.0,NaN,NaN,NaN,375.0,1759.0,NaN,NaN,1686.0,NaN,3445.0,3045.0

In [57]:
df_filtered = df[df["DataValueType"] == "Crude Rate"]  # Change for other types
pivot_df_crude = df_filtered.pivot_table(
    index=["YearStart", "LocationDesc", "Topic", "Question"], 
    columns="Stratification1",
    values="DataValue",
    aggfunc="mean"
).reset_index()
pivot_df_crude.head()

Stratification1,YearStart,LocationDesc,Topic,Question,Age 45-64,Age >=65,"American Indian or Alaska Native, non-Hispanic","Asian or Pacific Islander, non-Hispanic","Asian, non-Hispanic","Black, non-Hispanic",Female,"Hawaiian or Pacific Islander, non-Hispanic",Hispanic,Male,"Multiracial, non-Hispanic",Overall,"White, non-Hispanic"
0,2019,Alabama,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,46.5,335.6,NaN,NaN,NaN,77.10,154.10,NaN,NaN,171.60,NaN,162.20,198.30
1,2019,Alabama,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,79.4,519.6,NaN,NaN,NaN,139.00,229.60,NaN,NaN,285.60,NaN,255.50,307.20
2,2019,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,NaN,NaN,222.53,27.94,NaN,142.42,118.95,NaN,27.17,128.95,NaN,123.49,122.10
3,2019,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,NaN,NaN,NaN,NaN,NaN,16.45,15.49,NaN,NaN,13.54,NaN,14.60,14.52
4,2019,Alaska,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,21.3,164.9,111.90,NaN,NaN,NaN,82.60,NaN,NaN,58.00,NaN,70.00,71.50