In [45]:
# Imports --> Compare this with 0_data_cleaning --> Done
import pandas as pd

In [46]:
path = '/home/daniel.lien/dev/homework/data/U.S._Chronic_Disease_Indicators__CDI___2023_Release copy.csv'
df_all = pd.read_csv(path)
df_all.head()

/tmp/ipykernel_326062/3213538031.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all = pd.read_csv(path)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2010,2010,OR,Oregon,NVSS,Cardiovascular Disease,Mortality from heart failure,NaN,NaN,Number,...,41,CVD,CVD1_4,NMBR,RACE,AIAN,NaN,NaN,NaN,NaN
1,2019,2019,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,4,ALC,ALC1_1,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
2,2019,2019,OH,Ohio,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,39,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
3,2019,2019,US,United States,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,59,ALC,ALC1_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
4,2015,2015,VI,Virgin Islands,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,78,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN

In [47]:
# Drop Columns from entire dataset that are missing = Num of missing values == num of rows --> Completely empty
df = df_all.drop(columns=[
            'Response',  # Entire col is empty
            'StratificationCategory2', # Entire col is empty
            'Stratification2', # Entire col is empty
            'StratificationCategory3', # Entire col is empty
            'Stratification3', # Entire col is empty
            'ResponseID', # Entire col is empty
            'StratificationCategoryID2', # Entire col is empty
            'StratificationID2', # Entire col is empty
            'StratificationCategoryID3', # Entire col is empty
            'StratificationID3', # Entire col is empty
            'YearEnd', # We will use Year start instead
            'LocationAbbr', # We will use location instead
            'DataSource', #Not needed at this moment 
            'DataValueAlt', #Not needed, will use DataValue 
            'DataValueFootnoteSymbol', #Not needed at this moment 
            'DatavalueFootnote', #Not needed at this moment 
            'HighConfidenceLimit', #Not needed at this moment 
            'LowConfidenceLimit', #Not needed at this moment 
            'LocationID', # We will use Location
            'DataValueTypeID',  # Not needed 
            'TopicID' # we know this is copd
        ])
print(df.shape)

(1185676, 13)

In [48]:
# Now filter entier dataset for topic = 'Chronic Obstructive Pulmonary Disease'
topic = 'Chronic Obstructive Pulmonary Disease'
df = df[df['Topic'] == topic]

In [49]:
states_to_keep = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", 
                  "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", 
                  "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", 
                  "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
                  "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", 
                  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

df = df[df['LocationDesc'].isin(states_to_keep)]

In [50]:
# Drop All Unecessary Columns
df = df.drop(columns=[
            'Topic',
            'GeoLocation',
            'QuestionID',
            'StratificationCategoryID1',
            'StratificationID1',
            'DataValueUnit',
            'StratificationCategory1'
])

In [51]:
df = df[df['DataValueType'] == 'Number']

In [52]:
df = df[df['Question'] == 'Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >= 45 years']

In [53]:
df = df.dropna()

In [54]:
df = df.drop(columns=['DataValueType']) #drop data value type since we know this is NUMBER OF MORTALITY NOW

In [55]:
# Rename Columns to 
df.rename(columns={'YearStart': 'Year',
                    'LocationDesc': 'State',
                    'DataValue': 'Mortality',
                    'Stratification1': 'Stratification'}, inplace=True)

In [56]:
df = df[df['Year'] != 2010]

In [57]:
#Sort by state and year
df.sort_values(['State', 'Year'], inplace=True)

In [58]:
output_dir = '/home/daniel.lien/dev/homework/data/final_check/cleaned_copd_data_final.csv'
df.to_csv(output_dir, index=False)

In [59]:
medicaid_path = '/home/daniel.lien/dev/homework/Chronic_Disease_Indicators_Data_Visualization/workspaces/ashley/MEDICAID_AGGREGATE20.CSV'

In [60]:
df = pd.read_csv(medicaid_path)
df.head()

,Code,Item,Group,Region_Number,Region_Name,State_Name,Y1991,Y1992,Y1993,Y1994,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Average_Annual_Percent_Growth
0,1,Medicaid/Personal Health Care (Millions of Dol...,United States,0,United States,NaN,88921,103417,116453,126856,...,388256,405666,446921,484506,503382,516067,531782,552953,586914,6.7
1,1,Medicaid/Personal Health Care (Millions of Dol...,Region,1,New England,NaN,6676,7418,7768,8896,...,25512,26113,28519,30368,31616,31577,32910,32767,34183,5.8
2,1,Medicaid/Personal Health Care (Millions of Dol...,Region,2,Mideast,NaN,24821,28301,30979,33776,...,87340,88864,97912,103253,109981,117574,122226,123410,125408,5.7
3,1,Medicaid/Personal Health Care (Millions of Dol...,Region,3,Great Lakes,NaN,13820,16525,18627,19492,...,52941,56964,62039,66741,68168,70092,70563,74817,83497,6.4
4,1,Medicaid/Personal Health Care (Millions of Dol...,Region,4,Plains,NaN,5548,6569,7205,7910,...,25535,26266,27973,29466,30255,31077,32582,33444,34551,6.5

In [61]:
cols_to_drop = [
    'Code',
    'Region_Number',
    'Region_Name',
    'Y1991', 'Y1992', 'Y1993', 'Y1994','Y1995','Y1996','Y1997','Y1998','Y1999', 'Y2000', 'Y2001','Y2002','Y2003','Y2004','Y2005','Y2006','Y2007','Y2008','Y2009','Y2010',
    'Average_Annual_Percent_Growth'
]
df = df.drop(columns=cols_to_drop)

In [62]:
# Filter by 'Region' == 'State Name'
df = df[df['Group'] == 'State']

In [63]:
df = df.dropna()

In [64]:
df = df[df['State_Name'] != 'District of Columbia']

In [65]:
year_columns = [col for col in df.columns if col.startswith("Y")]  # Identifying year columns
df[year_columns] = df[year_columns].apply(pd.to_numeric, errors='coerce')

In [66]:
# Melt the DataFrame to long format
df_long = df.melt(id_vars=['State_Name'], value_vars=year_columns, 
                   var_name='Year', value_name='Expenses')

# Convert 'Year' to integer
df_long['Year'] = df_long['Year'].str.extract('(\\d+)').astype(int)

# Group by state and year, summing Medicaid expenses
df_grouped = df_long.groupby(['State_Name', 'Year'])['Expenses'].sum().reset_index()

In [67]:
# Rename Columns to 
df_grouped.rename(columns={'YearStart': 'Year',
                    'State_Name': 'State',
                    'Expenses': 'Medicaid_Spending',
                    }, inplace=True)

In [68]:
output_dir = '/home/daniel.lien/dev/homework/data/final_check/medicaid_data_cleaned.csv'
df_grouped.to_csv(output_dir, index=False)

In [69]:
median_income = '/home/daniel.lien/dev/homework/data/h08.xlsx'

In [70]:
df = pd.read_excel(median_income, skiprows=7)

In [71]:
#pandas automatically handled multi index 
df.columns = df.columns.map(str)
df = df.loc[:, ~df.columns.str.contains('^Unnamed: ')]

In [72]:
years_to_drop = ['2017 (40)', '2013 (39)']
df = df.drop(columns=years_to_drop)

In [73]:
import re
def extract_year(col):
    match = re.search(r'\b(19|20)\d{2}\b', str(col))
    return match.group(0) if match else col

df.columns = [extract_year(col) for col in df.columns]

In [74]:
#Drop
years_to_keep = [str(year) for year in range(2011,2021)]
#my 2013 is weird and 2020 is weird 
columns_to_keep = ['State'] + years_to_keep if 'State' in df.columns else years_to_keep
df = df[columns_to_keep]
df.head()

,State,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,NaN,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income
1,United States,50050,51020,51940,53660,56520,59040,61370,63180,68700,68010
2,Alabama,42590,43460,41380,42280,44510,47220,51110,49940,56200,54690
3,Alaska,57430,63650,61140,67630,75110,75720,72230,68730,78390,74750
4,Arizona,48620,47040,50600,49250,52250,57100,61130,62280,70670,67090

In [75]:
df = df.drop(index=0)
df.head()

,State,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,United States,50050,51020,51940,53660,56520,59040,61370,63180,68700,68010
2,Alabama,42590,43460,41380,42280,44510,47220,51110,49940,56200,54690
3,Alaska,57430,63650,61140,67630,75110,75720,72230,68730,78390,74750
4,Arizona,48620,47040,50600,49250,52250,57100,61130,62280,70670,67090
5,Arkansas,41300,39020,39920,44920,42800,45910,48830,49780,54540,50780

In [76]:
# Drop rows where 'State' is 'USA' or 'District of Columbia'
df = df[~df['State'].isin(['United States', 'District of Columbia'])]

df.head()

,State,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
2,Alabama,42590,43460,41380,42280,44510,47220,51110,49940,56200,54690
3,Alaska,57430,63650,61140,67630,75110,75720,72230,68730,78390,74750
4,Arizona,48620,47040,50600,49250,52250,57100,61130,62280,70670,67090
5,Arkansas,41300,39020,39920,44920,42800,45910,48830,49780,54540,50780
6,California,53370,57020,57530,60490,63640,66640,69760,70490,78100,77650

In [77]:
# Only keep the first half, take first 51 rows
df = df.iloc[:50]
df.shape

(50, 11)

In [78]:
df.columns

Index(['State', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020'],
      dtype='object')

In [79]:
df_long = df.melt(id_vars='State', var_name='Year', value_name='Median_Income')

In [80]:

df_long.head()

        State  Year Median_Income
0     Alabama  2011         42590
1      Alaska  2011         57430
2     Arizona  2011         48620
3    Arkansas  2011         41300
4  California  2011         53370

In [81]:
df_long.columns

Index(['State', 'Year', 'Median_Income'], dtype='object')

In [82]:
output_dir = '/home/daniel.lien/dev/homework/data/final_check/medianincome_temp.csv'
df_long.to_csv(output_dir, index=False)

In [83]:
medicaid = '/home/daniel.lien/dev/homework/data/final_check/medicaid_data_cleaned.csv'
medicaid_df = pd.read_csv(medicaid)
median_income = '/home/daniel.lien/dev/homework/data/final_check/medianincome_temp.csv'
median_income_df = pd.read_csv(median_income)  
copd = '/home/daniel.lien/dev/homework/data/final_check/cleaned_copd_data_final.csv'
copd_df = pd.read_csv(copd)

In [84]:
# Merge median income into COPD data
df_merged = copd_df.merge(median_income_df, on=['State', 'Year'], how='left')

# Merge Medicare spending into the result
df_merged = df_merged.merge(medicaid_df, on=['State', 'Year'], how='left')

In [85]:
df_merged = df_merged.drop(columns='Question')

In [86]:
df_merged.columns

Index(['Year', 'State', 'Mortality', 'Stratification', 'Median_Income',
       'Medicaid_Spending'],
      dtype='object')

In [87]:
# Re-Order
df_merged = df_merged[['Year', 'State', 'Stratification', 'Medicaid_Spending', 'Median_Income', 'Mortality']]

In [88]:
output_dir = '/home/daniel.lien/dev/homework/data/final_check/final_csv.csv'
df_merged.to_csv(output_dir, index=False)