In [5]:
import pandas as pd

In [6]:
# medicaid_path = "../../workspaces/MEDICAID_AGGREGATE20.CSV"
medicaid_path = '/home/daniel.lien/dev/homework/Chronic_Disease_Indicators_Data_Visualization/workspaces/MEDICAID_AGGREGATE20.CSV'

In [7]:
df = pd.read_csv(medicaid_path)

In [8]:
df.head()

,Code,Item,Group,Region_Number,Region_Name,State_Name,Y1991,Y1992,Y1993,Y1994,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Average_Annual_Percent_Growth
0,1,Medicaid/Personal Health Care (Millions of Dol...,United States,0,United States,NaN,88921,103417,116453,126856,...,388256,405666,446921,484506,503382,516067,531782,552953,586914,6.7
1,1,Medicaid/Personal Health Care (Millions of Dol...,Region,1,New England,NaN,6676,7418,7768,8896,...,25512,26113,28519,30368,31616,31577,32910,32767,34183,5.8
2,1,Medicaid/Personal Health Care (Millions of Dol...,Region,2,Mideast,NaN,24821,28301,30979,33776,...,87340,88864,97912,103253,109981,117574,122226,123410,125408,5.7
3,1,Medicaid/Personal Health Care (Millions of Dol...,Region,3,Great Lakes,NaN,13820,16525,18627,19492,...,52941,56964,62039,66741,68168,70092,70563,74817,83497,6.4
4,1,Medicaid/Personal Health Care (Millions of Dol...,Region,4,Plains,NaN,5548,6569,7205,7910,...,25535,26266,27973,29466,30255,31077,32582,33444,34551,6.5

In [9]:
df.shape

(600, 37)

In [10]:
df.columns

Index(['Code', 'Item', 'Group', 'Region_Number', 'Region_Name', 'State_Name',
       'Y1991', 'Y1992', 'Y1993', 'Y1994', 'Y1995', 'Y1996', 'Y1997', 'Y1998',
       'Y1999', 'Y2000', 'Y2001', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006',
       'Y2007', 'Y2008', 'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014',
       'Y2015', 'Y2016', 'Y2017', 'Y2018', 'Y2019', 'Y2020',
       'Average_Annual_Percent_Growth'],
      dtype='object')

In [12]:
df.describe()

,Code,Region_Number,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Average_Annual_Percent_Growth
count,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,...,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,598.000000
mean,5.500000,4.400000,889.206667,1034.181667,1164.541667,1268.561667,1362.501667,1445.096667,1513.503333,1583.161667,...,3882.565000,4056.663333,4469.188333,4845.065000,5033.798333,5160.673333,5317.825000,5529.521667,5869.116667,8.231773
std,2.874678,2.246868,4441.061044,5166.207101,5806.892632,6317.635909,6770.202570,7169.398444,7472.450175,7811.286327,...,18982.128708,19836.762166,21821.227147,23704.926264,24607.262070,25205.070206,25956.409041,26985.265948,28674.536348,3.549888
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,0.100000
25%,3.000000,2.750000,13.000000,16.000000,20.000000,24.000000,26.750000,28.000000,29.000000,31.000000,...,111.000000,114.750000,135.500000,153.750000,160.500000,169.000000,174.750000,188.750000,195.500000,6.100000
50%,5.500000,5.000000,92.500000,101.500000,129.000000,137.000000,147.500000,162.500000,170.500000,180.500000,...,496.000000,494.000000,574.000000,601.000000,620.000000,648.500000,674.000000,710.000000,730.500000,7.700000
75%,8.000000,6.000000,395.250000,442.250000,519.250000,586.000000,621.750000,665.500000,718.000000,747.250000,...,1858.000000,1909.750000,2145.000000,2292.500000,2337.250000,2501.250000,2589.250000,2724.750000,2927.250000,9.700000
max,10.000000,8.000000,88921.000000,103417.000000,116453.000000,126856.000000,136250.000000,144510.000000,151352.000000,158316.000000,...,388256.000000,405666.000000,446921.000000,484506.000000,503382.000000,516067.000000,531782.000000,552953.000000,586914.000000,26.600000

In [ ]:
# Medicaid Cleaning
"""
Drop NA
Filter by  'region == state'
Filter out non-states
group by state and year and sum all expenses  

Pivot to get by state and year 
"""