In [88]:
import pandas as pd

In [89]:
median_income = '/home/daniel.lien/dev/homework/data/h08.xlsx'

In [90]:
df = pd.read_excel(median_income, skiprows=7)

,State,2023,Unnamed: 2,2022,Unnamed: 4,2021,Unnamed: 6,2020 (41),Unnamed: 8,2019,...,1988,Unnamed: 76,1987 (21),Unnamed: 78,1986,Unnamed: 80,1985 (20),Unnamed: 82,1984 (19),Unnamed: 84
0,NaN,Median income,Standard error,Median income,Standard error,Median income,Standard error,Median income,Standard error,Median income,...,Median income,Standard error,Median income,Standard error,Median income,Standard error,Median income,Standard error,Median income,Standard error
1,United States,80610,385,74580,588,70780,368,68010,535,68700,...,27230,139,26060,127,24900,129,23620,128,22420,102
2,Alabama,60660,3993,59910,1934,56930,2294,54690,2563,56200,...,19950,912,19730,1147,19130,885,18330,760,17310,605
3,Alaska,98190,6112,89740,4842,81130,3967,74750,3557,78390,...,33100,1183,33230,1497,31360,1017,34780,1089,32360,1473
4,Arizona,82660,2723,73450,4123,70820,3394,67090,3409,70670,...,26440,843,26750,892,25500,718,23880,744,21430,609
5,Arkansas,63250,2451,53980,2376,50780,1440,50780,1837,54540,...,20170,706,18830,1008,18730,765,17450,764,15670,748
6,California,89870,1840,85300,1960,81580,1219,77650,1437,78100,...,30290,634,30150,538,29010,570,26980,350,25290,364
7,Colorado,96640,6194,89930,3790,84950,3155,83780,6019,72500,...,26210,1285,26480,1075,27190,926,28180,850,25800,805
8,Connecticut,92240,5980,90730,4245,80960,5261,79430,3602,87290,...,36210,1293,32860,1362,32720,1605,31090,1129,29950,1238
9,Delaware,86340,3867,80750,4160,68690,2919,70020,5283,74190,...,30510,1167,29240,875,25630,1212,22980,1366,25820,1027

In [91]:
#pandas automatically handled multi index 
df.columns = df.columns.map(str)
df = df.loc[:, ~df.columns.str.contains('^Unnamed: ')]

In [92]:
import re
def extract_year(col):
    match = re.search(r'\b(19|20)\d{2}\b', str(col))
    return match.group(0) if match else col

df.columns = [extract_year(col) for col in df.columns]

In [93]:
#Drop
years_to_keep = [str(year) for year in range(2011,2021)]
#my 2013 is weird and 2020 is weird 
columns_to_keep = ['State'] + years_to_keep if 'State' in df.columns else years_to_keep
df = df[columns_to_keep]
df.head()

,State,2011,2012,2013,2013,2014,2015,2016,2017,2017,2018,2019,2020
0,NaN,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income
1,United States,50050,51020,53590,51940,53660,56520,59040,61140,61370,63180,68700,68010
2,Alabama,42590,43460,47320,41380,42280,44510,47220,50870,51110,49940,56200,54690
3,Alaska,57430,63650,72470,61140,67630,75110,75720,77990,72230,68730,78390,74750
4,Arizona,48620,47040,52610,50600,49250,52250,57100,59700,61130,62280,70670,67090

In [94]:
df = df.drop(index=0)
df.head()

,State,2011,2012,2013,2013,2014,2015,2016,2017,2017,2018,2019,2020
1,United States,50050,51020,53590,51940,53660,56520,59040,61140,61370,63180,68700,68010
2,Alabama,42590,43460,47320,41380,42280,44510,47220,50870,51110,49940,56200,54690
3,Alaska,57430,63650,72470,61140,67630,75110,75720,77990,72230,68730,78390,74750
4,Arizona,48620,47040,52610,50600,49250,52250,57100,59700,61130,62280,70670,67090
5,Arkansas,41300,39020,39380,39920,44920,42800,45910,49750,48830,49780,54540,50780

In [95]:
# Drop rows where 'State' is 'USA' or 'District of Columbia'
df = df[~df['State'].isin(['United States', 'District of Columbia'])]

df.head()

,State,2011,2012,2013,2013,2014,2015,2016,2017,2017,2018,2019,2020
2,Alabama,42590,43460,47320,41380,42280,44510,47220,50870,51110,49940,56200,54690
3,Alaska,57430,63650,72470,61140,67630,75110,75720,77990,72230,68730,78390,74750
4,Arizona,48620,47040,52610,50600,49250,52250,57100,59700,61130,62280,70670,67090
5,Arkansas,41300,39020,39380,39920,44920,42800,45910,49750,48830,49780,54540,50780
6,California,53370,57020,60790,57530,60490,63640,66640,70040,69760,70490,78100,77650

In [96]:
# Only keep the first half, take first 51 rows
df = df.iloc[:50]
df.shape

(50, 13)

In [97]:
df.columns

Index(['State', '2011', '2012', '2013', '2013', '2014', '2015', '2016', '2017',
       '2017', '2018', '2019', '2020'],
      dtype='object')

In [98]:
df_long = df.melt(id_vars='State', var_name='Year', value_name='Median_Income')

In [99]:

df_long.head()

        State  Year Median_Income
0     Alabama  2011         42590
1      Alaska  2011         57430
2     Arizona  2011         48620
3    Arkansas  2011         41300
4  California  2011         53370

In [100]:
df_long.columns

Index(['State', 'Year', 'Median_Income'], dtype='object')

In [101]:
output_dir = '/home/daniel.lien/dev/homework/data/medianincome_temp.csv'
df_long.to_csv(output_dir, index=False)